app:
    resource: "@AppBundle/Controller/"
    type:     annotation

ctv_index:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }

admin:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   admin/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

api_articles:
    path:     api/articles
    defaults: { _controller: "AppBundle:Api:articles" }

api_user:
    path:     api/user
    defaults: { _controller: "AppBundle:Api:user" }

api_series_all:
    path:     api/series
    defaults: { _controller: "AppBundle:Api:obtenerSeries" }
    methods:  GET    

api_generos_all:
    path:     api/generos
    defaults: { _controller: "AppBundle:Api:obtenerGeneros" }
    methods:  GET        

api_titulos_all:
    path: api/titulos
    defaults: { _controller: "AppBundle:Api:obtenerTitulos" }
    methods: GET

api_titulos_serie:
    path: api/titulos_serie/{serie_id}
    defaults: { _controller: "AppBundle:Api:obtenerTitulosPorSerie" }
    methods: GET

api_titulos_serie:
    path: api/titulos_genero/{genero_id}
    defaults: { _controller: "AppBundle:Api:obtenerTitulosPorGenero" }
    methods: GET    

api_titulo_detalle:
    path: api/titulos/{id}
    defaults: { _controller: "AppBundle:Api:obtenerDetalleTitulo" }
    methods: GET

api_titulos_destacados:
    path: api/titulos/destacados/
    defaults: { _controller: "AppBundle:Api:obtenerTitulosDestacados" }
    methods: GET    