generos:
    path:     /
    defaults: { _controller: "AppBundle:Generos:index" }

generos_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Generos:show" }

generos_new:
    path:     /new
    defaults: { _controller: "AppBundle:Generos:new" }

generos_create:
    path:     /create
    defaults: { _controller: "AppBundle:Generos:create" }
    methods:  POST

generos_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Generos:edit" }

generos_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Generos:update" }
    methods:  [POST, PUT]

generos_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Generos:delete" }
    methods:  [POST, DELETE]
